Replace old ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,59 +1,73 @@
 name: CI
 
 on:
-  push:
-    branches:
-    - master
-
   pull_request:
-    branches:
-    - master
+  push:
+    paths-ignore:
+      - "docs/**"
+      - CHANGELOG.md
 
 jobs:
-  test:
-    runs-on: ubuntu-latest
-
+  unit-tests:
+    name: Unit Tests
+    runs-on: windows-latest
+    timeout-minutes: 10
     steps:
-    - uses: actions/checkout@v2
-      with:
-        submodules: true
+      - name: Checkout repository
+        uses: actions/checkout@v2.3.4
 
-    - uses: leafo/gh-actions-lua@v8
-      with:
-        luaVersion: "5.1"
+      - name: Install Roblox Studio
+        uses: OrbitalOwen/roblox-win-installer-action@1.1
+        with:
+          # throwaway cookie for public PR's, dw
+          cookie: ${{ secrets.ROBLOSECURITY || '_|WARNING:-DO-NOT-SHARE-THIS.--Sharing-this-will-allow-someone-to-log-in-as-you-and-to-steal-your-ROBUX-and-items.|_453BA25DDC50351B9452E45010925017BE2D120A821F2624D4DCF97A07254583CCB9B2302EB934A4DD96E96726025D5F262FFF7FE3E597AA0737C9CA5DA9195987576D50F85FFFC2B1A40549DD3E8D13CA7DCD6C5CACC2514B844E2705E625B2E86D97C45DB47DF16AA6ED5BF4A809EBB9529370BCA42597764CD94896E15D18B6C1CAF0483A3B6EE10EC309A849C70E0C34360BFF020C067DC6287EC72C353B41D3E4CD47AFD672CFB465F8D78C1261A720FAB679A90F05BF0350080BB5FE9471370D989A0E1ED977577F4218BF8DB2D19DB6A00D0EC63546A9EC885C4675107B495EBA4F8424730FCD2F2076580441EEC794F0E805357D7E649659429461BABB70730FA462A156BE8C9E9CE3CAE3AD856CAE5E4C31AAD6B866BB3781A03EE34B35C258E60BE293BA130385F0F9D777BC61424BCB69B08A17220EC085DCF53B1661A563E6E021F831425CBA8A22AFF3BF5BEF70' }}
+          token: ${{secrets.GITHUB_TOKEN}}
 
-    - uses: leafo/gh-actions-luarocks@v4
+      - name: Install Foreman
+        uses: rojo-rbx/setup-foreman@v1.0.1
+        with:
+          token: ${{secrets.GITHUB_TOKEN}}
 
-    - name: Install dependencies
-      run: |
-        luarocks install luafilesystem
-        luarocks install cluacov
-        luarocks install luacov-reporter-lcov
+      - name: Install Packages
+        shell: bash
+        run: wally install
 
-    - name: install code quality tools
-      uses: rojo-rbx/setup-foreman@v1
-      with:
-        version: "^1.0.1"
-        token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Build test place
+        run: rojo build test/test.project.json -o test.rbxl
 
-    - name: install and run darklua
-      run: |
-        cargo install --git https://gitlab.com/seaofvoices/darklua.git#v0.6.0
-        darklua process src/ src/ --format retain-lines
+      # Studio sometimes fails to load without these flag modifications as of 1/12/2022, apparently. https://github.com/rojo-rbx/run-in-roblox/issues/21
+      - name: Create fflag overrides
+        run: |
+          $flags = @{DFIntStudioUseNewLoginDataEndpointHundredthPercent=0; FFlagStudioUseNewLoginDataEndpoint=$false}
+          New-Item -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/' -Name "ClientSettings" -ItemType "directory"
+          New-Item -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/ClientSettings' -Name "ClientAppSettings.json"
+          $flags | ConvertTo-Json -depth 32| set-content -Path 'C:/Program Files (x86)/Roblox/Versions/version-*/ClientSettings/ClientAppSettings.json'
 
-    - name: Test
-      run: |
-        lua -lluacov test/lemur.lua
-        luacov -r lcov
+      - name: Run tests
+        shell: bash
+        run: run-in-roblox --place test.rbxl --script test/server/TestExecution.server.lua > test-out.txt
+        continue-on-error: true
 
-    - name: code quality
-      shell: bash
-      run: |
-        selene src
-        stylua -c src/
+      - name: Print test results
+        shell: bash
+        run: cat test-out.txt
 
-    - name: Report to Coveralls
-      uses: coverallsapp/github-action@1.1.3
-      with:
-        github-token: ${{ secrets.GITHUB_TOKEN }}
-        path-to-lcov: luacov.report.out
+      - name: Check test status
+        shell: bash
+        run: cat test-out.txt | grep "0 failed, 0 skipped" || (cat test-out.txt && exit 1)
+  linting:
+    name: Linting
+    runs-on: windows-latest
+    timeout-minutes: 10
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2.3.4
+
+      - name: Install Foreman
+        uses: rojo-rbx/setup-foreman@v1.0.1
+        with:
+          token: ${{secrets.GITHUB_TOKEN}}
+
+      - name: Run Selene
+        shell: bash
+        run: selene src
